---
# handlers file for my_namespace.my_role

- name: reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: update-locale
  command: update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

# 更新 apt 缓存
- name: update-apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
