---
# tasks file for gcslaoli.cloud.common

# 按 ansible_distribution 及 ansible_architecture 选择对应的操作系统文件
- name: 引入对应的操作系统文件
  include_tasks: "{{ ansible_distribution }}/{{ ansible_architecture }}.yml"
