---
- name: 当前为 Ubuntu
  debug:
    msg: "当前为 Ubuntu"
# 如果 ubuntu_mirror 变量不为空，则替换 /etc/apt/sources.list 中的archive.ubuntu.com为ubuntu_mirror变量的值
- name: 使用 {{ ubuntu_mirror }} 替换 /etc/apt/sources.list 中的archive.ubuntu.com
  replace:
    path: /etc/apt/sources.list
    regexp: 'archive.ubuntu.com'
    replace: '{{ ubuntu_mirror }}'
  when: ubuntu_mirror is defined and ubuntu_mirror != '' and ansible_architecture == "x86_64"

# 如果 ubuntu_mirror 变量不为空，则替换 /etc/apt/sources.list 中的security.ubuntu.com为ubuntu_mirror变量的值
- name: 使用 {{ ubuntu_mirror }} 替换 /etc/apt/sources.list 中的security.ubuntu.com
  replace:
    path: /etc/apt/sources.list
    regexp: 'security.ubuntu.com'
    replace: '{{ ubuntu_mirror }}'
  when: ubuntu_mirror is defined and ubuntu_mirror != '' and ansible_architecture == "x86_64"

# 如果 ubuntu_mirror 变量不为空，则替换 /etc/apt/sources.list 中的ports.ubuntu.com为ubuntu_mirror变量的值
- name: 使用 {{ ubuntu_mirror }} 替换 /etc/apt/sources.list 中的ports.ubuntu.com
  replace:
    path: /etc/apt/sources.list
    regexp: 'ports.ubuntu.com'
    replace: '{{ ubuntu_mirror }}'
  when: ubuntu_mirror is defined and ubuntu_mirror != '' and ansible_architecture == "aarch64"

# 更新软件包
- name: 更新软件包
  apt:
    update_cache: yes
    cache_valid_time: 3600

# 安装常用软件包
- name: 安装常用软件包
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - net-tools
    - iputils-ping
    - traceroute
    - iproute2
    - tzdata



# 设置时区为 {{ timezone }}
- name: 设置时区为 {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined and timezone != ''

